#
# The YAML file is a lightweight markup language file that supports all
# ROS parameter types. It's used by rosparam to load static parameters to
# the Parameter Server, which are commonly used to initialize part of a
# system and rarely change on run-time. Sometimes the user modifies this
# file before starting a node. This file is usually in the /config subdirectory
# of a package. Note that when dynamic reconfiguration is implemented for
# a package, most parameters will be dynamic, making this file barely used.
#
#                    _________ NOTES _________
#
# These can be used to replace the dynamic reconfigure server in case the
# system runs on a limited platform or for some other reason to have static
# instead of dynamic parameters. If that's not the case, keep them commented.
#

initial_current: 30  # Initial current amplitude

stim_limit: 110  # Max current among all channels

shift: 0  # Speed angle shift parameter

# Current amplitude relation/multiplier
stim_proportion: {
    'Ch1': 1.00, 'Ch2': 1.00,
    'Ch3': 0.50, 'Ch4': 0.50,
    'Ch5': 0.00, 'Ch6': 0.00,
    'Ch7': 1.00, 'Ch8': 1.00
}

# Angle range for each stim channel
Ch1AngleMin: 280
Ch1AngleMax: 20
Ch2AngleMin: 100
Ch2AngleMax: 200

Ch3AngleMin: 30
Ch3AngleMax: 105
Ch4AngleMin: 210
Ch4AngleMax: 285

Ch5AngleMin: 70
Ch5AngleMax: 170
Ch6AngleMin: 250
Ch6AngleMax: 350

Ch7AngleMin: 280
Ch7AngleMax: 20
Ch8AngleMin: 100
Ch8AngleMax: 200
