## These are not being used ##
#
filter_size: 20
gastrocnemius_max: 500
femoral_max: 500
speed_ref: 300

## Replacing the dynamic reconfigure server #
# Shift: 35

# Ch12: {
#   'Ch1_Angle_Min': 280,
#   'Ch1_Angle_Max': 20,
#   'Ch2_Angle_Min': 100,
#   'Ch2_Angle_Max': 200
# }

# Ch34: {
#     'Ch3_Angle_Min': 30,
#     'Ch3_Angle_Max': 105,
#     'Ch4_Angle_Min': 210,
#     'Ch4_Angle_Max': 285
# }

# Ch56: {
#     'Ch5_Angle_Min': 70,
#     'Ch5_Angle_Max': 170,
#     'Ch6_Angle_Min': 250,
#     'Ch6_Angle_Max': 350
# }

# Ch78: {
#     'Ch7_Angle_Min': 0,
#     'Ch7_Angle_Max': 0,
#     'Ch8_Angle_Min': 0,
#     'Ch8_Angle_Max': 0
# }