## These are not being used ##
#
# filter_size: 20
# gastrocnemius_max: 500
# femoral_max: 500
# speed_ref: 300

## Replacing the dynamic reconfigure server #
Shift: 35

Ch1: {
  'Ch1_Angle_Min': 280,
  'Ch1_Angle_Max': 20
}

Ch2: {
  'Ch2_Angle_Min': 100,
  'Ch2_Angle_Max': 200
}

Ch3: {
  'Ch3_Angle_Min': 30,
  'Ch3_Angle_Max': 105
}

Ch4: {
  'Ch4_Angle_Min': 210,
  'Ch4_Angle_Max': 285
}

Ch5: {
  'Ch5_Angle_Min': 70,
  'Ch5_Angle_Max': 170
}

Ch6: {
  'Ch6_Angle_Min': 250,
  'Ch6_Angle_Max': 350
}

Ch7: {
  'Ch7_Angle_Min': 280,
  'Ch7_Angle_Max': 20
}

Ch8: {
  'Ch8_Angle_Min': 100,
  'Ch8_Angle_Max': 200
}
