## These are not being used ##
#
filter_size: 20
gastrocnemius_max: 500
femoral_max: 500
speed_ref: 300

## Replacing the dynamic reconfigure server #
# Shift: 35

# Ch12: {
#   'Ch12_Angle_Odd_Min': 280,
#   'Ch12_Angle_Odd_Max': 20,
#   'Ch12_Angle_Even_Min': 100,
#   'Ch12_Angle_Even_Max': 200
# }

# Ch34: {
#     'Ch34_Angle_Odd_Min': 30,
#     'Ch34_Angle_Odd_Max': 105,
#     'Ch34_Angle_Even_Min': 210,
#     'Ch34_Angle_Even_Max': 285
# }

# Ch56: {
#     'Ch56_Angle_Odd_Min': 70,
#     'Ch56_Angle_Odd_Max': 170,
#     'Ch56_Angle_Even_Min': 250,
#     'Ch56_Angle_Even_Max': 350
# }

# Ch78: {
#     'Ch78_Angle_Odd_Min': 0,
#     'Ch78_Angle_Odd_Max': 0,
#     'Ch78_Angle_Even_Min': 0,
#     'Ch78_Angle_Even_Max': 0
# }