Ch12: {Ch1_Angle_Max: 20, Ch1_Angle_Min: 280, Ch2_Angle_Max: 200, Ch2_Angle_Min: 100}
Ch34: {Ch3_Angle_Max: 105, Ch3_Angle_Min: 30, Ch4_Angle_Max: 285, Ch4_Angle_Min: 210}
Ch56: {Ch5_Angle_Max: 170, Ch5_Angle_Min: 70, Ch6_Angle_Max: 350, Ch6_Angle_Min: 250}
Ch78: {Ch7_Angle_Max: 20, Ch7_Angle_Min: 280, Ch8_Angle_Max: 200, Ch8_Angle_Min: 100}
initial_current: 0
pulse_width: 500
shift: 0
stim_limit: 110
stim_proportion: {Ch1: 1.0, Ch2: 1.0, Ch3: 0.5, Ch4: 0.5, Ch5: 0.0, Ch6: 0.0, Ch7: 1.0,
  Ch8: 1.0}
