ch1_angle_max: 20
ch1_angle_min: 275
ch2_angle_max: 20
ch2_angle_min: 275
ch3_angle_max: 20
ch3_angle_min: 275
ch4_angle_max: 20
ch4_angle_min: 275
ch5_angle_max: 200
ch5_angle_min: 95
ch6_angle_max: 200
ch6_angle_min: 95
ch7_angle_max: 200
ch7_angle_min: 95
ch8_angle_max: 200
ch8_angle_min: 95
pulse_width: 500
racing_current: 30
ramp_end: 20
ramp_start: 25
shift: 10
stim_limit: 100
stim_proportion: {ch1: 1.0, ch2: 1.0, ch3: 0.0, ch4: 0.0, ch5: 0.0, ch6: 0.0, ch7: 1.0,
  ch8: 1.0}
training_current: 0
