Ch1AngleMax: 20
Ch1AngleMin: 280
Ch2AngleMax: 200
Ch2AngleMin: 100
Ch3AngleMax: 105
Ch3AngleMin: 30
Ch4AngleMax: 285
Ch4AngleMin: 210
Ch5AngleMax: 170
Ch5AngleMin: 70
Ch6AngleMax: 350
Ch6AngleMin: 250
Ch7AngleMax: 20
Ch7AngleMin: 280
Ch8AngleMax: 200
Ch8AngleMin: 100
initial_current: 30
pulse_width: 500
shift: 0
stim_limit: 110
stim_proportion:
  Ch1: 1.0
  Ch2: 1.0
  Ch3: 0.5
  Ch4: 0.5
  Ch5: 0.0
  Ch6: 0.0
  Ch7: 1.0
  Ch8: 1.0
